### ISSUE TITLE
zooming out

### ISSUE THREAD

**Issue by BaileySkinner-SOI** [schmidtocean/expedition_explorer#1]
Unable to zoom completely out to see the whole world map, this is most prominent on a mobile device (I was only able to test on an iPhone 13). Desktop browsers (Chrome, Safari, and Firefox) are only able to zoom out as far as one ocean basin.

**Comment by CorinneBassin-SOI** [comment]
changed zoom out level to 0;
Please review
- All desktop browsers should be able to see entire world
- mobile device should at least zoom out to more reasonable size

**Comment by BaileySkinner-SOI** [comment]
zooming out looks great on all browers and devices
