### ISSUE TITLE
cellular device orientation

### ISSUE THREAD

**Issue by BaileySkinner-SOI** [schmidtocean/expedition_explorer#2]
when turning the phone horizontally, the video box takes up a bit over half of the screen, and unable to see/scroll around well because of this

**Comment by CorinneBassin-SOI** [comment]
changes made.  4 separate viewing sizes now;
- Large-scale landscape screens and desktops should be the same as before
-  landscape phone should still have the video on left side of screen but smaller width then desktop
- phones in portrait should be as before with video at the bottom approx 300px tall not covering the info button
-  ipads turned to portrait will have the same orientation as a phone in portrait but video size will be increased

( knows issue with portrait for phones with width <300px, only known phone of this size is galaxy fold)

**Comment by BaileySkinner-SOI** [comment]
iPhone looks good when in landscape orientation, the size of the video box is much better and able to zoom out and scroll much better because of this.
